version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    working_dir: /app
    restart: always

  mongo:
    image: mongo:5
    container_name: db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: ${MONGO_NAME}
    volumes:
      - ./mongo:/data/posts
